[tool.poetry]
name = "bt-sdk"
version = "0.12.5"
description = "downgrade protobuf version"
authors = ["hengxin.liu <hengxin.liu@inceptio.ai>"]
readme = "README.md"
build = "build_ext.py"

include = [
    { path = "bt_sdk/**/*.so", format = "wheel" },
    { path = "bt_sdk/**/*.pyx" }
]

[tool.poetry.dependencies]
python = ">=3.11,<3.15"
toolz = "^1.0.0"
pandas = "^2.2.3"
pytest = "^8.3.5"
pytest-asyncio = "^0.26.0"
msgpack = "^1.1.0"
pyzmq = "^26.4.0"
typing-inspection = "^0.4.0"
ping3 = "^4.0.8"
typing-extensions = "^4.14.1"
annotated-types = "^0.7.0"
setuptools-cmake-helper = "^0.1.2"
pygments = "^2.19.2"
urllib3 = "^2.5.0"
reactivex = "^4.1.0"
cython = "^3.2.3"
pyarrow = "^22.0.0"
msgspec = "^0.20.0"
poetry-core = "^2.4.0"
polars = "^1.39.3"
setuptools = "77.0.1"
grpcio = ">=1.78.0"
# protobuf = "^7.35.0"
protobuf = ">=3.19,<7.0"
build = "^1.5.0"
numpy = "^2.4.6"
pydantic = ">=2.11.0"

[tool.poetry.group.build.dependencies]
wheel = "^0.41.0"
cmake = "^3.26.0"
pybind11 ="^3.0.1"
ninja = "^1.11.1"

#[tool.poetry.build]
#pre-build-script = "scripts/pre_build.py"  # 构建前运行
#post-build-script = "scripts/post_build.py" # 构建后运行

[[tool.poetry.source]]
name = "tuna"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
priority = "primary"  

[[tool.poetry.source]]
name = "devpi"
url = "http://localhost:3141/bt_sdk/dev/+simple/"
priority = "supplemental"

# [tool.setuptools]
# include-package-data = true # __init__

# [tool.setuptools.packages.find]
# where = ["."]
# include = ["bt_sdk*"]
# exclude = ["tests*", "docs*", "benchmarks*"]

# [tool.setuptools.package-data]
# "*" = ["*.pyx", "*.pxd", "*.so", "*.pyd", "*.h", "*.cpp", "*.proto", "*.pyi*"]


[build-system]
requires = ["poetry-core", "wheel", "pybind11", "cmake", "Cython>=3.0", "numpy", "setuptools"] # used to execute build.py
# build-backend =  "setuptools.build_meta" # 
build-backend = "poetry.core.masonry.api" # for pure python / scikit-build-core for cmake
