[build-system]
requires = ["poetry-core", "wheel", "pybind11", "cmake", "Cython>=3.0"]
build-backend =  "setuptools.build_meta" # "poetry.core.masonry.api" for pure python / scikit-build-core for cmake

[project] # used for setuptools
name = "bt-sdk"
version = "0.11.6"
description = "revise protocol and add more api in api.pyx"
authors = [
    {name = "hengxin.liu", email = "john@example.com"}
]
readme = "README.md"

[tool.poetry]
name = "bt-sdk"
version = "0.11.6"
description = "revise protocol and add more api in api.pyx"
authors = ["hengxin.liu <hengxin.liu@inceptio.ai>"]
readme = "README.md"
include = [
    "bt_sdk/core/lib/factor/lib/*.so",
    "bt_sdk/core/lib/factor/lib/*.dylib",
    "bt_sdk/core/lib/factor/lib/*.pyd"
]

[tool.poetry.dependencies]
python = "^3.11"
toolz = "^1.0.0"
pandas = "^2.2.3"
pytest = "^8.3.5"
pytest-asyncio = "^0.26.0"
msgpack = "^1.1.0"
devpi-client = "^7.2.0"
pyzmq = "^26.4.0"
typing-inspection = "^0.4.0"
pydantic-core = "2.16.3"
ping3 = "^4.0.8"
typing-extensions = "^4.14.1"
annotated-types = "^0.7.0"
setuptools-cmake-helper = "^0.1.2"
pygments = "^2.19.2"
pydantic = "2.6.4"
urllib3 = "^2.5.0"
reactivex = "^4.1.0"
cython = "^3.2.3"
pyarrow = "^22.0.0"
msgspec = "^0.20.0"
poetry-core = "^2.3.1"
polars = "^1.39.3"
setuptools = "77.0.1"
grpcio = "1.53.0"

[tool.poetry.group.build.dependencies]
wheel = "^0.41.0"
cmake = "^3.26.0"
pybind11 ="^3.0.1"
ninja = "^1.11.1"

#[tool.poetry.build]
#pre-build-script = "scripts/pre_build.py"  # 构建前运行
#post-build-script = "scripts/post_build.py" # 构建后运行

[[tool.poetry.source]]
name = "tuna"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
priority = "primary"  

[[tool.poetry.source]]
name = "devpi"
url = "http://localhost:3141/bt_sdk/dev/+simple/"
priority = "supplemental"

[tool.setuptools]
packages = ["bt_sdk", "bt_sdk.core", "bt_sdk.core.client", "bt_sdk.core.rpc.serialize"]
include-package-data = true 

[tool.setuptools.package-data]
"*" = ["*.pyx", "*.pxd", "*.so", "*.pyd", "*.h", "*.cpp", "*.proto", "*.pyi*"]
